// <auto-generated />
namespace MindfireSolutions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Table_Changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Table_Changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201904300947101_User_Table_Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
